apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/robertfer-bot/loony-argocd-public-repo.git
    path: nginx_yaml_files
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
